### ISSUE TITLE
Images not loading.

### ISSUE THREAD

**Issue by DiscordAnaxes** [ardasoyturk/twitter-profile-viewer#2]
It seems that the user banner and avatar are not being displayed properly. 

![image](https://user-images.githubusercontent.com/68460474/138574797-40eebe9e-66ce-4637-bda0-bc8ff25bbe3e.png)

OS: Win 10
Browser: Microsoft Edge Version 95.0.1020.30 (Official build) (64-bit)

**Comment by ardasoyturk** [comment]
![image](https://user-images.githubusercontent.com/33841775/138932065-f267e96d-a6d5-4220-b0d9-a03391c8ec1d.png)
Works properly on me, can you try again?

**Comment by DiscordAnaxes** [comment]
Ah ok. I've tried again on mobile data, and it seems to have worked. Probably something with my internet blocking the image link.
